version: '3.1'
services :
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: applicant
      POSTGRES_PASSWORD: temp123
      POSTGRES_DB: blog_db
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080